### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by BitcircuitEU** [Do0ks/Discord-Movie-Bot#7]
Hey there,

running Python 3.11 on Windows Server 2022
getting following error when using pip install discord:
```
Traceback (most recent call last):
  File "C:\Plex\Plex-Bot.py", line 200, in <module>
    bot.loop.run_until_complete(setup())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\discord\client.py", line 145, in __getattr__
    raise AttributeError(msg)
AttributeError: loop attribute cannot be accessed in non-async contexts. Consider using either an asynchronous main function and passing it to asyncio.run or using asynchronous initialisation hooks such as Client.setup_hook
```

getting following error when using old version of discord.py (173) as in requirements.txt
```
Traceback (most recent call last):
  File "C:\Plex\Plex-Bot.py", line 9, in <module>
    from discord import app_commands
ImportError: cannot import name 'app_commands' from 'discord' (C:\Program Files\Python311\Lib\site-packages\discord\__init__.py)
```

**Comment by Do0ks** [comment]
Please try the new committed code. 

However, I believe this is because of Discord.py v2 Changes requiring devs to manage the event loop using modern async patterns (such as asyncio.run)
